# Site settings
title: Book Giveaway

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bookgiveaway.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
